export interface NPCDef {
  id: string;
  name: string;
  title: string;
  area: string;
  position: [number, number, number];
  bodyColor: string;
  accentColor: string;
  hairColor: string;
  dialogue: string[];
}

export const NPC_DATA: NPCDef[] = [
  // ── SUNFIELD PLAINS ─────────────────────────────────────────────
  {
    id: 'elder',
    name: 'Elder Osric',
    title: 'Village Elder',
    area: 'field',
    position: [6, 0, 3],
    bodyColor: '#7b5e3a',
    accentColor: '#d4a870',
    hairColor: '#e8e8e8',
    dialogue: [
      "Adelynn! Thank the light you've come to Sunfield Village.",
      "The Shadow Sorcerer Malgrath shattered the Crown of Radiance into three Crystal Shards.",
      "Each Shard holds a Bound Spirit prisoner. Free the spirits and restore the Crown!",
      "One shard lies hidden here in Sunfield Plains — search for the glowing chest to the north.",
      "The second shard is deep inside Whisper Woods. The third burns in Ashrock Summit.",
      "Once you have all three, face Malgrath in his Lair to the north!",
    ],
  },
  {
    id: 'merchant',
    name: 'Zarko',
    title: 'Travelling Merchant',
    area: 'field',
    position: [8, 0, 12],
    bodyColor: '#5d4037',
    accentColor: '#ff8f00',
    hairColor: '#212121',
    dialogue: [
      "Step right up! Zarko's Wares — finest deals in all of Aldenmere!",
      "I stock heart potions, shurikens, and whatever else a hero might need.",
      "Tap the SHOP button to browse my wares. Rupees are the currency!",
      "Heard the Bound Spirit Solara used to light up this whole valley every dawn. Miss those days...",
    ],
  },
  {
    id: 'lily',
    name: 'Lily',
    title: 'Flower Keeper',
    area: 'field',
    position: [13, 0, 7],
    bodyColor: '#f48fb1',
    accentColor: '#f8bbd0',
    hairColor: '#c8a060',
    dialogue: [
      "Oh, Adelynn! The shadows have been growing darker every night.",
      "I saw a golden glow north of the village — near the old stone chest!",
      "Collect 4 heart pieces for a new heart container — they're scattered everywhere.",
      "Please hurry... the flowers are wilting without the Crown's light.",
    ],
  },
  {
    id: 'tomas',
    name: 'Tomas',
    title: 'Village Guard',
    area: 'field',
    position: [9, 0, 11],
    bodyColor: '#37474f',
    accentColor: '#78909c',
    hairColor: '#4e342e',
    dialogue: [
      "Halt! Oh — it's you, Adelynn. Sorry, on edge with all the shadow creatures lately.",
      "Those Shadow Slimes have been crawling up from the ground since the Crown broke.",
      "Tap the attack button quickly for a basic swing — hold for a Spin Attack!",
      "Use the weapon button to fire your equipped sub-weapon. Stay sharp!",
    ],
  },
  {
    id: 'brynn',
    name: 'Brynn',
    title: 'Innkeeper',
    area: 'field',
    position: [2, 0, 8],
    bodyColor: '#8d6e63',
    accentColor: '#bcaaa4',
    hairColor: '#bf360c',
    dialogue: [
      "Welcome to the Amber Lantern! Best stew in Aldenmere, though the kitchen's been cold since the Crown broke.",
      "My grandmother used to say that the Bound Spirit Zephyr carried warm breezes over these fields.",
      "I saw King Aldric's royal messenger ride through weeks ago. Never came back.",
      "Rest when you can, Adelynn. Even heroes need sleep.",
    ],
  },
  {
    id: 'nyla',
    name: 'Nyla',
    title: 'Wandering Seer',
    area: 'field',
    position: [-6, 0, 5],
    bodyColor: '#4a148c',
    accentColor: '#ce93d8',
    hairColor: '#1a0030',
    dialogue: [
      "The threads of fate glow bright around you, young Adelynn...",
      "I see three shards of blazing light — and one sorcerer shrouded in void.",
      "Malgrath fears the seven Bound Spirits. He caged them because they are the only power that can undo him.",
      "When Lumis, the Spirit of Light, is freed — Malgrath's shadow armour will crack. Remember that.",
    ],
  },
  {
    id: 'aldric',
    name: 'King Aldric',
    title: 'Exiled King of Aldenmere',
    area: 'field',
    position: [-10, 0, 12],
    bodyColor: '#b8860b',
    accentColor: '#ffd700',
    hairColor: '#e8e8d0',
    dialogue: [
      "I failed my kingdom, Adelynn. I let Malgrath grow powerful while I feasted in my hall.",
      "The Crown of Radiance was my family's sacred charge for eleven generations. I let it shatter.",
      "Take this knowledge: the Bound Spirit Lumis gave our family the crown — and only her light can restore it.",
      "Go. Do what I could not.",
    ],
  },
  {
    id: 'petra',
    name: 'Petra',
    title: 'Blacksmith',
    area: 'field',
    position: [-4, 0, 15],
    bodyColor: '#4e342e',
    accentColor: '#ff7043',
    hairColor: '#212121',
    dialogue: [
      "Been smithing since I could hold a hammer. Never seen darkness eat metal like this.",
      "Malgrath's creatures corrode steel on contact. The blades we forge last three fights, then crumble.",
      "Your Crystal Sword is different — it draws from the same source as the Crown. Won't corrode.",
      "I found a special upgrade stone in the desert. It's yours, if you survive long enough to use it.",
    ],
  },
  // ── WHISPER WOODS ───────────────────────────────────────────────
  {
    id: 'mira',
    name: 'Mira',
    title: 'Forest Botanist',
    area: 'forest',
    position: [10, 0, 14],
    bodyColor: '#2e7d32',
    accentColor: '#66bb6a',
    hairColor: '#4e342e',
    dialogue: [
      "Shh... you'll disturb the ancient spirits of the forest.",
      "I've studied these woods for years. Something extraordinary pulses at its heart.",
      "The Shard of Dusk — it sits in a chest at the very center of Whisper Woods.",
      "Beware the Briar Wolves. They're not natural creatures — Malgrath's corruption twisted them.",
      "There's a Fairy Fountain to the south-east of the forest — it will fully restore you!",
    ],
  },
  {
    id: 'gwynn',
    name: 'Gwynn',
    title: 'Root Herbalist',
    area: 'forest',
    position: [-8, 0, 10],
    bodyColor: '#1b5e20',
    accentColor: '#a5d6a7',
    hairColor: '#6d4c41',
    dialogue: [
      "These roots I'm harvesting normally glow faintly with Thornwick's blessing. Not anymore.",
      "Thornwick — the Spirit of the Wild — has been silent since Malgrath took the Shard.",
      "Every plant in this forest feels it. The bark has gone cold. The mushrooms smell of ash.",
      "Collect every heart piece you can find. This forest is not safe.",
    ],
  },
  {
    id: 'ryn',
    name: 'Ryn',
    title: 'Hermit Sage',
    area: 'forest',
    position: [-14, 0, 4],
    bodyColor: '#3e2723',
    accentColor: '#a1887f',
    hairColor: '#bdbdbd',
    dialogue: [
      "...I have lived in these woods for forty years and I have never seen darkness like this.",
      "The seven Bound Spirits were woven into the Crown long before Aldenmere was a kingdom.",
      "Solara, Thornwick, Embris, Glacira, Lumis, Zephyr, Cragus — seven aspects of the world's balance.",
      "You carry all seven hopes with you, girl. Do not fail them.",
    ],
  },
  {
    id: 'finn',
    name: 'Finn',
    title: 'Forest Scout',
    area: 'forest',
    position: [5, 0, -8],
    bodyColor: '#33691e',
    accentColor: '#8bc34a',
    hairColor: '#795548',
    dialogue: [
      "I've been scouting these woods for the village militia. The creatures are migrating inward.",
      "I found tracks — something enormous moved through the northern grove three nights ago.",
      "If you're going to the heart of the woods, take the eastern trail. Fewer ambush points.",
      "I left a cache of arrows near the big hollow oak. Help yourself.",
    ],
  },
  // ── ASHROCK SUMMIT ──────────────────────────────────────────────
  {
    id: 'kael',
    name: 'Kael',
    title: 'Desert Miner',
    area: 'desert',
    position: [-12, 0, -6],
    bodyColor: '#5d4037',
    accentColor: '#8d6e63',
    hairColor: '#3e2723',
    dialogue: [
      "Whew, this heat... you sure you want to be out here, lass?",
      "I've mined these dunes for twenty years. Never seen anything like that orange glow.",
      "The Shard of Ember — it burns north of the rock pillars in an ancient chest.",
      "Those Ember Scorpions are new. Malgrath's fire corrupted the desert scorpions. They're much bigger now.",
    ],
  },
  {
    id: 'daxar',
    name: 'Daxar',
    title: 'Blast-Crafter',
    area: 'desert',
    position: [-6, 0, -14],
    bodyColor: '#bf360c',
    accentColor: '#ff8a65',
    hairColor: '#212121',
    dialogue: [
      "Careful where you step — I've got powder charges drying in the sun!",
      "I used to sell my craft to the miners. Now the whole summit's overrun with Malgrath's creatures.",
      "Embris, the Spirit of the Forge — they say she taught the first smiths to work metal and fire.",
      "If you find the Shard of Ember... please free her. These rocks aren't right without her warmth.",
    ],
  },
  {
    id: 'priya',
    name: 'Priya',
    title: 'Water-Seller',
    area: 'desert',
    position: [-4, 0, -10],
    bodyColor: '#0277bd',
    accentColor: '#81d4fa',
    hairColor: '#37474f',
    dialogue: [
      "Water! Clean, cold water — last barrel I managed to haul from the valley spring.",
      "Glacira, the Spirit of Frost, used to keep a hidden spring of pure water under this summit.",
      "Since she's been trapped... the spring dried up. This desert is getting worse by the week.",
      "Clear us a safe route when you can, hero. The children haven't had a clean drink in three days.",
    ],
  },
  // ── MALGRATH'S LAIR ─────────────────────────────────────────────
  {
    id: 'calla',
    name: 'Sister Calla',
    title: 'Sanctuary Keeper',
    area: 'boss',
    position: [-4, 0, 8],
    bodyColor: '#fce4ec',
    accentColor: '#f48fb1',
    hairColor: '#f5f5f5',
    dialogue: [
      "You made it this far... I never dared hope.",
      "This used to be a sanctuary. Malgrath tore out the light and left only the Void Wraiths to patrol.",
      "The Fairy Fountain still works — hidden in the north corner. He couldn't corrupt something that pure.",
      "Go. Face Malgrath. The whole kingdom's future rests on your next few steps.",
    ],
  },
  {
    id: 'corvax',
    name: 'Corvax',
    title: 'Former Shadow Lieutenant',
    area: 'boss',
    position: [8, 0, -4],
    bodyColor: '#1a0030',
    accentColor: '#7c4dff',
    hairColor: '#311b92',
    dialogue: [
      "...I served Malgrath for six years. I believed his promises of a new age.",
      "Then I saw what he did to the seven Bound Spirits.",
      "He doesn't want a new age. He wants a dead one. A world of silence.",
      "His weak point is the Crown fragment at his chest. Adelynn... end this. For all of us.",
    ],
  },
  // ── ECHOING CAVES ───────────────────────────────────────────────
  {
    id: 'grotto',
    name: 'Old Grotto',
    title: 'Cave Hermit',
    area: 'cave',
    position: [4, 0, -6],
    bodyColor: '#607d8b',
    accentColor: '#90a4ae',
    hairColor: '#bdbdbd',
    dialogue: [
      "Decades in these caves... the echoes used to carry songs. Now they carry screams.",
      "The Magic Mirror in this cave belonged to the Seer of Aldenmere. It shows you the way home.",
      "Cave Demons hunt by sound. Move slowly and they'll miss you. Run and they'll be on you instantly.",
      "I've seen braver souls than you enter the deeper tunnels and not come out.",
    ],
  },
  {
    id: 'wick',
    name: 'Wick',
    title: 'Spelunker',
    area: 'cave',
    position: [-6, 0, 8],
    bodyColor: '#455a64',
    accentColor: '#b0bec5',
    hairColor: '#4e342e',
    dialogue: [
      "Best torches in Aldenmere and even my flame won't stop shaking in this dark.",
      "Found a vein of Moonstone crystals in the east tunnel — worth a fortune normally.",
      "With the Crown broken, nothing has normal value anymore. What's treasure when the world might end?",
      "There's a second exit to the north passage. Leads out near the jungle. Shortcut, if you're brave.",
    ],
  },
  // ── JUNGLE LABYRINTH ────────────────────────────────────────────
  {
    id: 'zuri',
    name: 'Zuri',
    title: 'Jungle Tracker',
    area: 'jungle',
    position: [8, 0, -10],
    bodyColor: '#1b5e20',
    accentColor: '#69f0ae',
    hairColor: '#000000',
    dialogue: [
      "The jungle has twelve layers. Most outsiders never get past the third.",
      "Jungle Trolls are territorial. Strike first and run. Never let them pin you against a tree.",
      "The vines here move. Not the wind — they actually reach. I've seen them drag away full-grown men.",
      "The Spirit Zephyr used to keep the vines in check. Without her blessing, they're untamed now.",
    ],
  },
  {
    id: 'isela',
    name: 'Isela',
    title: 'Jungle Shrine Keeper',
    area: 'jungle',
    position: [-10, 0, 6],
    bodyColor: '#004d40',
    accentColor: '#80cbc4',
    hairColor: '#3e2723',
    dialogue: [
      "This shrine was dedicated to Thornwick and Zephyr both — nature and sky in harmony.",
      "I've maintained it for thirty years. The carvings still glow faintly, even now.",
      "If you carry the spirit of both land and wind in your heart, the jungle will open a path for you.",
      "Listen for the rumble of the waterfall to the west. That's where the old power sleeps.",
    ],
  },
  // ── ICE MOUNTAINS ───────────────────────────────────────────────
  {
    id: 'frigga',
    name: 'Frigga',
    title: 'Mountain Guide',
    area: 'ice',
    position: [6, 0, 4],
    bodyColor: '#b3e5fc',
    accentColor: '#e1f5fe',
    hairColor: '#f5f5f5',
    dialogue: [
      "Without Speed Boots, you'll slip on the ice every few steps. They're in the ice temple to the north.",
      "Ice Wolves hunt in threes. Kill the lead wolf and the others scatter.",
      "Glacira's tears are literally frozen in the cliffs here. Beautiful and heartbreaking.",
      "In the old days, travellers lit bonfires at every pass. Glacira's warmth made it possible. Not anymore.",
    ],
  },
  {
    id: 'boras',
    name: 'Boras',
    title: 'Frost Rune Scholar',
    area: 'ice',
    position: [-8, 0, -6],
    bodyColor: '#0288d1',
    accentColor: '#4fc3f7',
    hairColor: '#e0e0e0',
    dialogue: [
      "These runes in the ice walls — they predate Aldenmere by thousands of years.",
      "They describe the first pact between humans and the Bound Spirits. A covenant of balance.",
      "Malgrath didn't just break the Crown. He violated a covenant written in the bones of this world.",
      "The world itself wants him stopped. Every element you wield is the world fighting back through you.",
    ],
  },
  // ── VOLCANO HEIGHTS ─────────────────────────────────────────────
  {
    id: 'soras',
    name: 'Soras',
    title: 'Lava Fisher',
    area: 'volcano',
    position: [10, 0, 6],
    bodyColor: '#bf360c',
    accentColor: '#ff7043',
    hairColor: '#212121',
    dialogue: [
      "Lava fishing — the only job hotter than being a hero. The magma eels fetch good rupees.",
      "Lava Beasts wake when they sense heartbeats. Move between the cold stone patches.",
      "I've seen bigger creatures in the caldera. Things that don't have names yet.",
      "The Embris Forge is deeper in. Embris, the Spirit of the Forge, shaped this volcano with her own hands.",
    ],
  },
  {
    id: 'cindra',
    name: 'Cindra',
    title: 'Volcano Cartographer',
    area: 'volcano',
    position: [-6, 0, 10],
    bodyColor: '#d84315',
    accentColor: '#ff8a65',
    hairColor: '#4e342e',
    dialogue: [
      "I've mapped every tunnel and vent in this volcano. Forty years of work.",
      "The lava flow shifted three months ago — right when Malgrath took Embris.",
      "She controlled the flow. Without her guidance, the magma does whatever it wants.",
      "The eastern tunnel leads to an ancient forge room. Something powerful rests there.",
    ],
  },
  // ── SKY CITADEL ─────────────────────────────────────────────────
  {
    id: 'aero',
    name: 'Aero',
    title: 'Wind Knight',
    area: 'sky',
    position: [12, 0, -8],
    bodyColor: '#b3e5fc',
    accentColor: '#81d4fa',
    hairColor: '#e0f7fa',
    dialogue: [
      "The Sky Citadel was built on solidified clouds by the Wind Knights of the old order.",
      "Zephyr, the Bound Spirit of Wind, keeps these clouds solid. Without her... we're drifting lower every week.",
      "Thunder Birds are Malgrath's aerial patrols. They move in formation. Break the formation and they lose coordination.",
      "The Storm Sword was forged up here in the eye of the greatest storm of the last century.",
    ],
  },
  {
    id: 'celeste',
    name: 'Celeste',
    title: 'Cloud Weaver',
    area: 'sky',
    position: [-10, 0, 10],
    bodyColor: '#e1f5fe',
    accentColor: '#b3e5fc',
    hairColor: '#f5f5f5',
    dialogue: [
      "I weave clouds into cloth. Sky-silk — lightest material in the world.",
      "Zephyr used to guide every thread. Now my fingers are numb and the clouds won't hold shape.",
      "I heard someone found a Magic Cape in the dungeon below the citadel. Made of pure sky-silk.",
      "A cape woven from sky-silk grants brief invincibility. Malgrath would hate for you to have that.",
    ],
  },
  // ── SHADOW REALM ────────────────────────────────────────────────
  {
    id: 'vesper',
    name: 'Vesper',
    title: 'Shadow Realm Survivor',
    area: 'shadow',
    position: [8, 0, 6],
    bodyColor: '#1a0030',
    accentColor: '#9c27b0',
    hairColor: '#311b92',
    dialogue: [
      "I've been trapped here for three months. The darkness feeds on will to live.",
      "Lumis, the Bound Spirit of Light — her cage is close. I can feel it. A warm pulse in the cold void.",
      "Shadow Slimes multiply when ignored. Kill them quickly or you'll be overwhelmed.",
      "If you find a way out... take me with you. Please.",
    ],
  },
  {
    id: 'umbra',
    name: 'Umbra',
    title: 'Keeper of Void Lore',
    area: 'shadow',
    position: [-8, 0, -6],
    bodyColor: '#0a0018',
    accentColor: '#7c4dff',
    hairColor: '#1a0030',
    dialogue: [
      "The Shadow Realm exists between heartbeats of the world. Malgrath tore it open and stepped through.",
      "Every shadow creature here was once something else — something living that lost its light.",
      "Malgrath's true weakness is light that remembers itself. Light that knows what it was before the dark.",
      "Free Lumis. Everything else will follow.",
    ],
  },
  // ── SWAMP TEMPLE (dungeon4) ──────────────────────────────────────
  {
    id: 'reed',
    name: 'Reed',
    title: 'Swamp Priest',
    area: 'dungeon4',
    position: [4, 0, 8],
    bodyColor: '#33691e',
    accentColor: '#76ff03',
    hairColor: '#1b5e20',
    dialogue: [
      "This temple was built to honour the water spirits who blessed the wetlands.",
      "The Swamp Guardian devoured three of my brothers before I could seal the inner gate.",
      "The Flippers of the Deep are inside. With them, you can swim through flooded passages.",
      "Water is life and death here. The Guardian controls both. Do not let it drag you under.",
    ],
  },
  {
    id: 'lira',
    name: 'Lira',
    title: 'Water Sprite',
    area: 'dungeon4',
    position: [-6, 0, -4],
    bodyColor: '#00bcd4',
    accentColor: '#80deea',
    hairColor: '#e0f7fa',
    dialogue: [
      "I am one of the last uncorrupted water spirits in the temple.",
      "The Swamp Guardian was once our protector. Now it seeks to drown everything it was sworn to guard.",
      "Find the three water seals and activate them. That will weaken the Guardian's bond to the swamp.",
      "Swift and silent — that is how the swamp is crossed safely.",
    ],
  },
  {
    id: 'marsh',
    name: 'Marsh',
    title: 'Lost Cartographer',
    area: 'dungeon4',
    position: [8, 0, -8],
    bodyColor: '#4caf50',
    accentColor: '#a5d6a7',
    hairColor: '#3e2723',
    dialogue: [
      "I came to map the Swamp Temple and got turned around three times. The corridors shift!",
      "The walls move when you're not looking. I've marked what I can but don't trust the map fully.",
      "Fishmen patrol the flooded lower sections. They're fast in water, slow on land — use that.",
      "There's a hidden room behind the third waterfall. I found it by accident.",
    ],
  },
  // ── SKULL WOODS (dungeon5) ──────────────────────────────────────
  {
    id: 'mortis',
    name: 'Mortis',
    title: 'Bone Keeper',
    area: 'dungeon5',
    position: [4, 0, 6],
    bodyColor: '#bdbdbd',
    accentColor: '#9e9e9e',
    hairColor: '#e0e0e0',
    dialogue: [
      "The Skull Woods were never pleasant. But they were honest. Now they're... hungry.",
      "The Skull Lord binds every skeleton here to his will. Defeat him and the undead collapse.",
      "The Fire Rod rests in the inner sanctum. The old pyromancer placed it there to keep the darkness at bay.",
      "Undead fear fire above all else. Remember that when you face the hordes.",
    ],
  },
  {
    id: 'spectra',
    name: 'Spectra',
    title: 'Haunted Spirit',
    area: 'dungeon5',
    position: [-6, 0, -6],
    bodyColor: '#e0e0e0',
    accentColor: '#f5f5f5',
    hairColor: '#bdbdbd',
    dialogue: [
      "I died here fifty years ago and couldn't leave. The Skull Lord made sure of that.",
      "I've watched him build his army for decades. Every creature that dies in these woods joins his ranks.",
      "The only thing he fears is bright fire. He hasn't felt warmth in centuries.",
      "Free me too, when you defeat him. Please. I'm so tired of this dark.",
    ],
  },
  // ── THIEVES' LAIR (dungeon6) ────────────────────────────────────
  {
    id: 'pickwick',
    name: 'Pickwick',
    title: 'Imprisoned Thief',
    area: 'dungeon6',
    position: [6, 0, 8],
    bodyColor: '#795548',
    accentColor: '#a1887f',
    hairColor: '#212121',
    dialogue: [
      "The Thief King locked me up when I tried to steal from him. Bit ironic for a thief.",
      "This lair has eleven levels of traps. I know every one — I helped design some.",
      "The Bug-catching Net is in the vault on level six. The King uses it to capture creatures for his menagerie.",
      "I'll show you the safe path through the traps if you get me out of here first.",
    ],
  },
  {
    id: 'silka',
    name: 'Silka',
    title: 'Phantom Guild Defector',
    area: 'dungeon6',
    position: [-8, 0, 4],
    bodyColor: '#4a148c',
    accentColor: '#ce93d8',
    hairColor: '#1a0030',
    dialogue: [
      "The Phantom Guild has served Malgrath for three years. We didn't know what we were signing up for.",
      "The Thief King convinced us it was just politics. Then we saw what Malgrath does to his prisoners.",
      "I'm done. The Net, the vaults, the traps — I'll tell you everything.",
      "The King's armour has one weak spot: the gap between his left pauldron and breastplate. Hit there.",
    ],
  },
  // ── ICE PALACE (dungeon7) ───────────────────────────────────────
  {
    id: 'glacella',
    name: 'Glacella',
    title: 'Ice Palace Historian',
    area: 'dungeon7',
    position: [4, 0, -8],
    bodyColor: '#e1f5fe',
    accentColor: '#b3e5fc',
    hairColor: '#f5f5f5',
    dialogue: [
      "The Ice Palace was Glacira's home. She built it crystal by crystal over a thousand years.",
      "Malgrath tore through its gates in a single night and caged her inside her own creation.",
      "She is still here, you can feel her — the ice remembers her touch.",
      "The Ice Rod was her gift to worthy champions. She would want you to have it.",
    ],
  },
  {
    id: 'cryos',
    name: 'Cryos',
    title: 'Ice Golem Guardian',
    area: 'dungeon7',
    position: [-6, 0, 6],
    bodyColor: '#b3e5fc',
    accentColor: '#e3f2fd',
    hairColor: '#e1f5fe',
    dialogue: [
      "I am Cryos. Glacira shaped me from the palace's foundation stone. I still serve her will.",
      "The Ice Palace Guardian you must defeat is not Glacira — it is her shadow, twisted by Malgrath.",
      "Glacira is the warmth beneath the ice. The Guardian is the cold without her heart.",
      "Defeat it and Glacira will be freed. She asked me to tell you: she is not afraid.",
    ],
  },
  // ── MISERY MIRE (dungeon8) ──────────────────────────────────────
  {
    id: 'quagmire',
    name: 'Quagmire',
    title: 'Mire Wanderer',
    area: 'dungeon8',
    position: [6, 0, 4],
    bodyColor: '#558b2f',
    accentColor: '#aed581',
    hairColor: '#3e2723',
    dialogue: [
      "Been walking the Misery Mire for a week. Can't find the edge. The mire doesn't want me to leave.",
      "The Mire Beast shifts form — it copied my shape for a while. That was unpleasant.",
      "Ether Medallion's power is locked inside the deepest chamber. Ancient sky-magic sealed in crystal.",
      "The quicksand patches glow slightly in the dark. Step only where there's no glow.",
    ],
  },
  {
    id: 'siltia',
    name: 'Siltia',
    title: 'Marsh Spirit',
    area: 'dungeon8',
    position: [-8, 0, -6],
    bodyColor: '#827717',
    accentColor: '#f9a825',
    hairColor: '#4e342e',
    dialogue: [
      "This marsh was a paradise once. Rich soil, singing frogs, silver fish.",
      "The Mire Beast rose from the deepest bog and devoured all of it.",
      "It consumes identity. The creatures here have forgotten what they were. I remember — barely.",
      "The Ether Medallion can freeze even the bog itself. Use it well.",
    ],
  },
  // ── TURTLE ROCK (dungeon9) ──────────────────────────────────────
  {
    id: 'torrath',
    name: 'Torrath',
    title: 'Dragon Lore Keeper',
    area: 'dungeon9',
    position: [8, 0, -6],
    bodyColor: '#bf360c',
    accentColor: '#ff7043',
    hairColor: '#000000',
    dialogue: [
      "The Turtle Dragon died here defending us from the first Shadow incursion, three thousand years ago.",
      "Its body became this mountain. Its bones became the tunnels. Its spirit became the Bombos Medallion.",
      "The Dragon Overlord is its hatched offspring — born from an egg left in the dragon's skull.",
      "It has fed on lava and resentment for centuries. It is very, very angry.",
    ],
  },
  {
    id: 'pyra',
    name: 'Pyra',
    title: 'Lava Walker',
    area: 'dungeon9',
    position: [-6, 0, 8],
    bodyColor: '#e64a19',
    accentColor: '#ffab91',
    hairColor: '#bf360c',
    dialogue: [
      "The tunnels through Turtle Rock are a labyrinth of lava tubes and dragon-claw scratches.",
      "Fire Drakes nest in the upper chambers. They guard the Bombos Medallion out of pure instinct.",
      "The Dragon Overlord's one weakness: the cold crystal on its throat. That crystal is its anchor to life.",
      "Strike the crystal three times and the Overlord will lose its ability to regenerate.",
    ],
  },
  // ── PALACE OF DARKNESS (dungeon10) ─────────────────────────────
  {
    id: 'vorath',
    name: 'Vorath',
    title: 'Shadow Court Scholar',
    area: 'dungeon10',
    position: [6, 0, 6],
    bodyColor: '#1a0030',
    accentColor: '#7c4dff',
    hairColor: '#311b92',
    dialogue: [
      "I studied the Shadow Court for twenty years before I understood what it truly was.",
      "The Palace of Darkness is built from crystallised despair — every stone is a stolen hope.",
      "The Shadow Lord was not born this way. He volunteered. He believed darkness was power.",
      "The Dipsgram Medallion here is the counter to everything this palace stands for. Lightning in the dark.",
    ],
  },
  {
    id: 'lumen',
    name: 'Lumen',
    title: 'Trapped Light Keeper',
    area: 'dungeon10',
    position: [-8, 0, -4],
    bodyColor: '#fff9c4',
    accentColor: '#fff176',
    hairColor: '#f5f5f5',
    dialogue: [
      "I carry the last candle in the Palace of Darkness. The Shadow Lord hates me for it.",
      "Light doesn't just illuminate — it remembers. Every beam is a memory of the sun.",
      "The Bound Spirit Lumis spoke to me once through this flame. She says she is not afraid.",
      "She said: 'The one carrying both sword and crown-fragment will know what to do at the end.'",
    ],
  },
  // ── MALGRATH'S FORTRESS (dungeon11) ────────────────────────────
  {
    id: 'solara',
    name: 'Solara',
    title: 'Freed Spirit of Light',
    area: 'dungeon11',
    position: [4, 0, 10],
    bodyColor: '#fff8e1',
    accentColor: '#ffd54f',
    hairColor: '#f9a825',
    dialogue: [
      "Adelynn... you freed me. I can feel the others — they're close.",
      "Malgrath has consumed fragments of all three Crown shards. His form is unstable, but vast.",
      "Together, all seven of us can weaken the void surrounding him enough for your blade to reach.",
      "End it. Not for vengeance — for every living thing that deserves to see the dawn again.",
    ],
  },
  {
    id: 'lumis',
    name: 'Lumis',
    title: 'Bound Spirit of Radiance',
    area: 'dungeon11',
    position: [-6, 0, 8],
    bodyColor: '#fffde7',
    accentColor: '#ffee58',
    hairColor: '#fff9c4',
    dialogue: [
      "I gave the first Crown to the first King of Aldenmere. I trusted humans to guard it.",
      "That trust was not misplaced — it was merely tested beyond imagining.",
      "Malgrath is almost here. His true form has no body — only will and hunger.",
      "But will and hunger can be ended. You have ended them before. Do it once more, Adelynn.",
    ],
  },
  {
    id: 'warden',
    name: 'Warden Thael',
    title: 'Fortress Prison Warden',
    area: 'dungeon11',
    position: [8, 0, -6],
    bodyColor: '#37474f',
    accentColor: '#b0bec5',
    hairColor: '#212121',
    dialogue: [
      "I... I don't know why I'm still here. Malgrath's power keeps me at my post.",
      "I have kept prisoners in this fortress for twelve years. All of them were innocent.",
      "The final door to Malgrath's sanctum is sealed by all three Crown shards working in reverse.",
      "Your three Crystal Shards should override the seal. Go. End this. Please.",
    ],
  },
  // ── EXTRA FIELD NPCs ────────────────────────────────────────────
  {
    id: 'cobbler',
    name: 'Old Cobbler Vern',
    title: 'Shoemaker',
    area: 'field',
    position: [4, 0, 16],
    bodyColor: '#6d4c41',
    accentColor: '#d7ccc8',
    hairColor: '#9e9e9e',
    dialogue: [
      "Forty years I've cobbled boots for Aldenmere. These days I cobble for refugees.",
      "Speed Boots — now those were Glacira's gift to the swift of heart. No stitching can match her craft.",
      "I heard the Crown's light used to make the leather pliable. Work easier. Better results.",
      "Safe travels, girl. And if your boots ever wear out — you know where to find me.",
    ],
  },
  {
    id: 'yenna',
    name: 'Yenna',
    title: 'Harvest Keeper',
    area: 'field',
    position: [-8, 0, 16],
    bodyColor: '#827717',
    accentColor: '#f9a825',
    hairColor: '#795548',
    dialogue: [
      "I'm trying to keep the crops growing but the soil won't drink anymore.",
      "The Spirit Solara warmed the earth every spring. Now the seeds just sit there, cold.",
      "My grandmother used to say that a handful of sunfield grain could feed a family for a week under the Crown's light.",
      "Whatever you're doing, Adelynn — please hurry. We have three weeks of grain left, maybe four.",
    ],
  },
  {
    id: 'oryn',
    name: 'Oryn',
    title: 'Retired Knight',
    area: 'field',
    position: [-14, 0, 6],
    bodyColor: '#546e7a',
    accentColor: '#90a4ae',
    hairColor: '#bdbdbd',
    dialogue: [
      "Forty battles under my belt and I'm watching a child carry the kingdom's fate. Strange times.",
      "In my day we trained for decades before the king trusted us with even a patrol route.",
      "Your Crystal Sword has edge memory — it learns from every strike. Don't waste that on reckless swings.",
      "The spin attack — hold attack until you feel it charge. Release at full spin. That's the technique I'd teach a knight.",
    ],
  },
  // ── EXTRA FOREST NPC ───────────────────────────────────────────
  {
    id: 'dendros',
    name: 'Dendros',
    title: 'Ancient Tree Speaker',
    area: 'forest',
    position: [14, 0, 6],
    bodyColor: '#33691e',
    accentColor: '#dcedc8',
    hairColor: '#6d4c41',
    dialogue: [
      "The oldest oak in these woods is three thousand years old. It remembers the first age of the Bound Spirits.",
      "I speak the tree-tongue — not magic, just patience and sixty years of listening.",
      "The forest wants you to succeed, Adelynn. The roots are parting to make your path easier.",
      "Thornwick speaks through these trees even now. Listen carefully in the deepest grove.",
    ],
  },
  // ── EXTRA DESERT NPCs ─────────────────────────────────────────
  {
    id: 'zane',
    name: 'Zane',
    title: 'Sand Drifter',
    area: 'desert',
    position: [8, 0, -12],
    bodyColor: '#d7ccc8',
    accentColor: '#efebe9',
    hairColor: '#4e342e',
    dialogue: [
      "I've crossed the Ashrock Summit twelve times. Never once found what I was looking for.",
      "Funny thing — now I know what I was looking for was the person who would save it.",
      "The dunes shift every seven years. Every map of this place is wrong. Trust your compass.",
      "Ember Scorpions avoid the area around the central obelisk. That's your safest rest spot.",
    ],
  },
  {
    id: 'nasira',
    name: 'Nasira',
    title: 'Desert Oracle',
    area: 'desert',
    position: [14, 0, -4],
    bodyColor: '#8d6e63',
    accentColor: '#ffccbc',
    hairColor: '#4e342e',
    dialogue: [
      "The desert has a heartbeat. You can hear it if you press your ear to the sand at midnight.",
      "Embris, Spirit of the Forge, once heated these sands from below. The desert was warm even at night.",
      "The sand serpents follow warmth. With Embris caged, they've grown erratic and dangerous.",
      "I have seen your path in the patterns of blown sand. You will succeed. But it will cost you something.",
    ],
  },
  // ── EXTRA BOSS NPC ─────────────────────────────────────────────
  {
    id: 'herald',
    name: 'Herald Dorn',
    title: "Malgrath's Captured Messenger",
    area: 'boss',
    position: [6, 0, 12],
    bodyColor: '#b0bec5',
    accentColor: '#eceff1',
    hairColor: '#37474f',
    dialogue: [
      "I carried a message to Malgrath demanding he release the Bound Spirits. He made me carry it back — forever.",
      "He bound the letter to my hand. I can't drop it. Can't read it. But I can feel it getting heavier.",
      "His sanctum has three layers of void shields. Each Crystal Shard you carry will dissolve one shield.",
      "When you face him — don't hesitate. Hesitation is where he lives.",
    ],
  },
  // ── EXTRA CAVE NPC ─────────────────────────────────────────────
  {
    id: 'calcite',
    name: 'Calcite',
    title: 'Crystal Miner',
    area: 'cave',
    position: [8, 0, 6],
    bodyColor: '#78909c',
    accentColor: '#cfd8dc',
    hairColor: '#546e7a',
    dialogue: [
      "See these crystals? They used to glow with the Crown's light. Now they're just pretty rocks.",
      "I mine them anyway. Habit. And because the rhythmic tapping keeps the darkness away, mentally.",
      "There's a vein of rare moonstone behind the fourth stalactite cluster. Worth good rupees to the right buyer.",
      "Cave Trolls can't see well. They track by sound and smell. Sprinkle cave dust on yourself — kills your scent.",
    ],
  },
  // ── EXTRA JUNGLE NPCs ─────────────────────────────────────────
  {
    id: 'kwame',
    name: 'Kwame',
    title: 'Jungle Alchemist',
    area: 'jungle',
    position: [6, 0, 10],
    bodyColor: '#1b5e20',
    accentColor: '#b9f6ca',
    hairColor: '#212121',
    dialogue: [
      "I've spent years extracting medicines from jungle plants. Half my notes are unusable now.",
      "The plants that once healed now cause rashes. Malgrath's corruption reverses their nature.",
      "I found a plant that still works — Sunheart Fern. Tiny, easy to miss. Tastes awful, heals fast.",
      "Brew it with cave water and you get something close to a full-heal potion. Spread the word.",
    ],
  },
  {
    id: 'tamsin',
    name: 'Tamsin',
    title: 'Lost Pilgrim',
    area: 'jungle',
    position: [-14, 0, -8],
    bodyColor: '#5d4037',
    accentColor: '#a1887f',
    hairColor: '#f5f5f5',
    dialogue: [
      "I set out for the Jungle Shrine six weeks ago. I have no idea where it is.",
      "I've been living on jungle berries and avoiding the creatures at night by climbing the largest tree I can find.",
      "The Hookshot would help in this terrain enormously. I've seen it described in the old shrine texts.",
      "When this is over, I'm going to write a very strongly worded letter to whoever designed this jungle.",
    ],
  },
  // ── EXTRA ICE NPC ─────────────────────────────────────────────
  {
    id: 'halvard',
    name: 'Halvard',
    title: 'Glacier Shepherd',
    area: 'ice',
    position: [12, 0, -8],
    bodyColor: '#cfd8dc',
    accentColor: '#eceff1',
    hairColor: '#f5f5f5',
    dialogue: [
      "I keep the mountain yaks. They used to follow Glacira's warmth up the passes every spring.",
      "Now they huddle together and won't move. Can't say I blame them.",
      "Frost Wraiths appear at the summits after dark. They can't cross flowing water — use the streams as barriers.",
      "When Glacira is freed, the passes will clear. Until then, no one's getting through the upper mountain.",
    ],
  },
  // ── EXTRA VOLCANO NPC ─────────────────────────────────────────
  {
    id: 'ignara',
    name: 'Ignara',
    title: 'Magma Sculptor',
    area: 'volcano',
    position: [4, 0, -10],
    bodyColor: '#dd2c00',
    accentColor: '#ff9e80',
    hairColor: '#bf360c',
    dialogue: [
      "I sculpt in magma. Very few can. It requires perfect timing, immense patience, and no eyebrows.",
      "The volcano used to give me shapes — Embris guided the flow into forms. Art as collaboration.",
      "Now the magma does what it wants. My last work collapsed into a lava pool. Two years of work.",
      "The Hammer — the Forge Hammer in the inner temple — it was Embris's personal tool. Take it.",
    ],
  },
  // ── EXTRA SKY NPC ─────────────────────────────────────────────
  {
    id: 'stratos',
    name: 'Stratos',
    title: 'Sky Cartographer',
    area: 'sky',
    position: [4, 0, 12],
    bodyColor: '#e1f5fe',
    accentColor: '#80d8ff',
    hairColor: '#e0f7fa',
    dialogue: [
      "I've mapped every cloud formation in the known sky. None of them are natural anymore.",
      "Malgrath seeded the upper clouds with shadow-mist three months ago. It's slowly working its way down.",
      "The sky citadel has a storm compass on the top spire. It still points toward Zephyr's cage.",
      "If you free Zephyr first, she can clear the skies and give every other spirit's location. She sees everything from up here.",
    ],
  },
  // ── EXTRA SHADOW NPC ──────────────────────────────────────────
  {
    id: 'null',
    name: 'The Nameless One',
    title: 'Entity of the Void',
    area: 'shadow',
    position: [0, 0, -12],
    bodyColor: '#0a0018',
    accentColor: '#310038',
    hairColor: '#000000',
    dialogue: [
      "...",
      "You still have a name. That means there is still time.",
      "Malgrath offered me power. I accepted. Now I have no name, no face, no memory of warmth.",
      "Do not make my mistake. No power is worth what you lose to get it.",
    ],
  },
  // ── EXTRA DUNGEON NPCs (one per dungeon4-11) ──────────────────
  {
    id: 'puddle',
    name: 'Puddle',
    title: 'Swamp Child',
    area: 'dungeon4',
    position: [-4, 0, 12],
    bodyColor: '#4caf50',
    accentColor: '#c8e6c9',
    hairColor: '#795548',
    dialogue: [
      "I fell into the swamp chasing a glowing frog. It led me here on purpose, I think.",
      "The frog sat by the Flippers chest and croaked until I tried to pick them up. Then it disappeared.",
      "There's a secret ledge above the second waterfall. I hid there when the Fishmen came through.",
      "If you find a way out, will you carry me? My legs are too short to jump the gaps.",
    ],
  },
  {
    id: 'ashbone',
    name: 'Ashbone',
    title: 'Former Knight, Now Undead',
    area: 'dungeon5',
    position: [10, 0, -4],
    bodyColor: '#9e9e9e',
    accentColor: '#e0e0e0',
    hairColor: '#bdbdbd',
    dialogue: [
      "I remember dying here. The Skull Lord raised me before I finished the thought.",
      "I still have my sense of self, somehow. The Lord's magic isn't perfect.",
      "He hates that — a skeleton with opinions. I think that's why he keeps me near the entrance. Makes an example of me.",
      "End him quickly and we all rest. I'm so tired of walking these halls.",
    ],
  },
  {
    id: 'vex',
    name: 'Vex',
    title: 'Master Lockpick',
    area: 'dungeon6',
    position: [2, 0, -10],
    bodyColor: '#37474f',
    accentColor: '#78909c',
    hairColor: '#212121',
    dialogue: [
      "Been picking locks since age seven. First time I've been on the wrong side of one.",
      "Small Keys are everywhere in this lair if you know where to look. Check behind the tapestries.",
      "The Thief King's master vault has seventeen locks. His ego required it. Use the Bug Net to snag his key ring.",
      "The trick with his armour is to get inside his rhythm. He attacks in threes. Dodge two, strike on three.",
    ],
  },
  {
    id: 'frostine',
    name: 'Frostine',
    title: 'Ice Architect',
    area: 'dungeon7',
    position: [10, 0, 6],
    bodyColor: '#b3e5fc',
    accentColor: '#e1f5fe',
    hairColor: '#f5f5f5',
    dialogue: [
      "I designed these ice-bridge chambers for Glacira herself. Now they're full of her enemies.",
      "The pressure-sensitive floors crack when enemies walk them — they crack for you too. Step to the edges.",
      "The Ice Palace Guardian moves in predictable arcs. Count four beats between sweeps.",
      "When Glacira is free, she said she would personally restore every chamber. I'll hold her to that.",
    ],
  },
  {
    id: 'bog',
    name: 'Bog',
    title: 'Mire Alchemist',
    area: 'dungeon8',
    position: [2, 0, -10],
    bodyColor: '#558b2f',
    accentColor: '#ccff90',
    hairColor: '#33691e',
    dialogue: [
      "The Misery Mire produces the rarest reagents in Aldenmere. Also the most dangerous.",
      "Mire sap, when distilled, can dissolve even enchanted armour. I learned this the hard way.",
      "The Mire Beast absorbs the properties of whatever it has recently devoured. Watch what it's eaten.",
      "If it absorbed mud — slow but tanky. If it absorbed a flying creature — fast but fragile. Adapt accordingly.",
    ],
  },
  {
    id: 'crag',
    name: 'Crag',
    title: 'Dragon Tamer (Retired)',
    area: 'dungeon9',
    position: [2, 0, 10],
    bodyColor: '#bf360c',
    accentColor: '#ffccbc',
    hairColor: '#212121',
    dialogue: [
      "Tamed seven dragons in my prime. Then the eighth one ate my notes and I retired.",
      "The Dragon Overlord is special — it remembers the war. Dragons have long memories.",
      "It will test you three times before going all-out. Survive the tests and it will respect you.",
      "Use the Bombos Medallion in the stone chamber — the explosion will crack its shell, exposing the throat crystal.",
    ],
  },
  {
    id: 'inkwell',
    name: 'Inkwell',
    title: 'Shadow Court Archivist',
    area: 'dungeon10',
    position: [-4, 0, -8],
    bodyColor: '#1a0030',
    accentColor: '#b39ddb',
    hairColor: '#311b92',
    dialogue: [
      "I've archived every decree, every judgment, every execution order in the Shadow Court.",
      "Forty-seven years of records. Not one act of mercy. Not one.",
      "The Shadow Lord believes records justify power. They don't. They condemn it.",
      "The Dipsgram Medallion's lightning is pure moral clarity — it only strikes what is truly dark. Use it freely.",
    ],
  },
  {
    id: 'emberglow',
    name: 'Emberglow',
    title: 'Spirit Fragment of Embris',
    area: 'dungeon11',
    position: [0, 0, -8],
    bodyColor: '#ff6f00',
    accentColor: '#ffe57f',
    hairColor: '#f57f17',
    dialogue: [
      "A piece of me escaped Malgrath's cage. Just enough to reach you here.",
      "Tell Embris — tell myself — that the forge still burns. It never went cold.",
      "In the final battle, call on all seven of us together. Our voices combined will shatter the void.",
      "We were woven into this world for moments exactly like this. We are ready.",
    ],
  },
];
